### ISSUE TITLE
Failed to instantiate component or class "yii\symfonymailer\Mailer::class".

### ISSUE THREAD

**Issue by metola** [yiisoft/yii2-symfonymailer#10]
Hi, If I add :: class show the error:
```Failed to instantiate component or class "yii\symfonymailer\Mailer::class".```

but if I not use ::class work well
``` 'class' => 'yii\symfonymailer\Mailer',```

I belive that is need change in Readme.

By the way, I change from 'yii\swiftmailer\Mailer' to 'yii\symfonymailer\Mailer' and for the moment all work well, this is my changes:
With Swiftmailer;
```	
	'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'transport' =>
                [
                    'class' => 'Swift_SmtpTransport',
                    'host' => 'email-smtp.eu-west-1.amazonaws.com',
                    'username' => '****',
                    'password' => '****',
                    'port' => '587',
                    'encryption' => 'tls',
                ]
        ],
```
and with Symfony:
```
'mailer' => [
            'class' => 'yii\symfonymailer\Mailer',
            'transport' =>
                [
                    'dsn' => 'ses+smtp://USERNAME:PASSWORD@email-smtp.eu-west-1.amazonaws.com',
                ]
        ],		
```

**Comment by samdark** [comment]
When you add `::class` do you remove quotes around the name?

**Comment by metola** [comment]
I´m idiot , yes it is.

**Comment by c7v** [comment]
Не помогло, у меня PhpStorm подсказывает что класса вообще нет.

**Comment by Swanty** [comment]
> Не помогло, у меня PhpStorm подсказывает что класса вообще нет.

Did you run composer install?  

Also, note the missing slash `\` in front of `yii` in previous comments, maybe try:
```
'class' => \yii\symfonymailer\Mailer::class,
```

**Comment by c7v** [comment]
> Did you run composer install?

On the same day I noticed that the class was not installed. @samdark Александр, а разве этот класс не устанавливается сразу при развёртывании Yii2 Advance?

**Comment by asmythe** [comment]
Here's my config:

```
'mailer' => [
    'class' => \yii\symfonymailer\Mailer::class,
    'useFileTransport' => false,
    'viewPath' => '@common/mail',
    'transport' => [
		'scheme' => 'smtps',
		'dsn'=>'<dsn info>',
    ],
]

```
Works perfectly on my Mac, but when I run it from my AWS Linux 2 instance, it won't instantiate. I'm guessing this is a case issue, since the Mac is not case sensitive and Linux is, but I can't figure it out. Anyone got any pointers for me?

<img width="744" alt="Screenshot 2023-02-15 at 12 03 47 PM" src="https://user-images.githubusercontent.com/3144947/219100580-d03226f2-3e93-44f2-8a28-c1f4dac5c8c7.png">

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-app-advanced/blob/master/composer.json#L20
