### ISSUE TITLE
No Email sent, no error, send() returns true

### ISSUE THREAD

**Issue by 1Luc1** [yiisoft/yii2-symfonymailer#12]
### What steps will reproduce the problem?
`config/web.php` :

```
$config = [
   ...
   'components' => [
      ...
      'mailer' => require(__DIR__ . '/mailer.php'),
      ...
   ],
   ...
]
```
`config/mailer.php` :
```
<?php

$params = require(__DIR__ . '/params.php');

return [
    'class' => \yii\symfonymailer\Mailer::class,
    'transport' => [
        'host' => 'smtp.gmail.com',
        'username' => $params['adminEmail'],
        'password' => '********',
        'port' => '465',
        'options' => ['ssl' => true],
    ],
    'messageConfig' => [
        'from' => $params['adminEmail'], //'bcc' => '<bbc email>',
    ],
];
```
Method to send email:

```
public function sendEmail() {
    $mailer = Yii::$app->mailer;
    $oldViewPath = $mailer->viewPath;
    $mailer->viewPath = "@app/mail";
    $isSent = $mailer->compose('testEmail')
                    ->setTo($this->email)
                    ->setSubject(Yii::t('dev', 'Email Test Send'))
                    ->send();
    
    $mailer->viewPath = $oldViewPath;
    return $isSent;
}

```
`
$this->email` comes from a form

### What's expected?
Email **will** be send. `->send()` method returns **true**.

### What do you get instead?
Email **won't** be send. `-> send()` method returns **true**.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.44
| Yii SymfonyMailer version | 2.0.0
| SymfonyMailer version     | 6.0.2
| PHP version             | 8.0.13
| Operating system        | Manjaro

I switched from `yiisoft/yii2-swiftmailer": "~2.1.2` . Sending email with swiftmailer worked.
Do I miss additional configuration? As stated from my config I'm trying to send from/over gmail account.

**Comment by Krakozaber** [comment]
I apologize, I made a mistake in the implementation of logging, I will correct myself. 

Pay attention to the configuration example in the README.MD you don't have the 'scheme' parameter specified.
`'scheme' => 'smtp'`

#13

**Comment by 1Luc1** [comment]
Thanks for the hi t. I'll try it as soon as I'm at home.

About the scheme config, is there any further reading about the values which can be set? Could't find anything. Maybe to add some usefull link or info about it to the readme?

**Comment by Krakozaber** [comment]
https://github.com/symfony/symfony-docs/blob/5.4/mailer.rst

Transport can be created in different ways

1. Configure it yourself by implementing `Symfony\Component\Mailer\Transport\TransportInterface`
2. In the configuration, set the `dsn` parameter from [Symfony-docs](https://github.com/symfony/symfony-docs/blob/5.4/mailer.rst), for example, in your case, you can use `'dsn' => 'gmail+smtp://USERNAME:PASSWORD@default'`
3. In the configuration, set all params for create [DSN](https://github.com/symfony/mailer/blob/5.4/Transport/Dsn.php)

**Comment by samdark** [comment]
I've tagged 2.0.1.
