### ISSUE TITLE
Classes defined as final

### ISSUE THREAD

**Issue by karelvasicek** [yiisoft/yii2-symfonymailer#20]
Extension classes should not be defined as `final` IMHO.

**Comment by samdark** [comment]
Do you have a certain issue with it?

**Comment by karelvasicek** [comment]
> Extension classes...

I meant classes of _this_ extension.

> Do you have a certain issue with it?

Well...

```
PHP Fatal error:  Class app\modules\messages\components\mailer\Mailer may not inherit from final class (yii\symfonymailer\Mailer)
```

**Comment by karelvasicek** [comment]
> What do you customize in your mailer?

`sendMessage()` method + we have some additional logic for sending emails via queue there. We could probably change the logic, but using the `final` keyword makes conversion from https://github.com/yiisoft/yii2-swiftmailer much more complicated.

**Comment by karelvasicek** [comment]
The previous comment was related to `Mailer` class, we have some other customizations in `Message` class too.

**Comment by Krakozaber** [comment]
Are you sure that this logic should be in SendMessage(), and not outside of it?

**Comment by karelvasicek** [comment]
@Krakozaber 

> Are you sure that this logic should be in SendMessage(), and not outside of it?

We don't have the queue logic in `SendMessage()` (we have some other modifications related to logging and testing there), we use different method for it. But even this method is in the `Mailer`class. As I wrote, we also use customized `Message` with additional class properties and methods. I'm not sure what was the real reason for using the `final` keyword for these classes and we could newly use f.ex. adapter for it, but it definitely makes conversion from `yii2-swiftmailer` (based on not maintained Swiftmailer) much more complicated.

**Comment by Krakozaber** [comment]
@karelvasicek 

Example of using queues https://github.com/shaqman/yii2-queue-mailer, there is no need to modify an existing class. You should do the same.

**Comment by karelvasicek** [comment]
@Krakozaber , thanks for the advice, but as I wrote - `Mailer` class could be changed on our side, queue logic could be extracted, but we still have customized `sendMessage()` method. Using _single_ `Yii::$app->mailer` component for sending 
"standard" emails and queued emails just makes more sense to me. In addition, we have also customized the `Message` what's my much bigger concern. TBH I don't understand much why such "compatibility break" (in comparison with `yii2-swiftmailer`) was introduced.

Anyway, would you remove the `final` keyword from those classes? That's what I suggested, but if you don't accept this suggestion, we can of course close this issue and we'll have to proceed with another approach.

**Comment by Krakozaber** [comment]
@samdark the decision is yours..

**Comment by Krakozaber** [comment]
#21

**Comment by karelvasicek** [comment]
Thanks @Krakozaber

**Comment by samdark** [comment]
I'm fine removing it for Yii2 package.

**Comment by Krakozaber** [comment]
@samdark tag it pliz

**Comment by samdark** [comment]
Done.
