### ISSUE TITLE
Define a default transport / error without transport

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2-symfonymailer#22]
A suggestion:

When switching from `yii2-swiftmailer`, there is a pitfall: You have to add a transport config option. The swiftmailer extension defaulted to `sendmail` transport:

https://github.com/yiisoft/yii2-swiftmailer/blob/master/src/Mailer.php#L175-L177

I think it would be a good idea to either add a sane default (sendmail or php setting?), or throw an error due to invalid config.

The main problem with this is that is just fails silently with no transport specified, even returning `true` on `send()`, suggesting that it has been successful, when it was not.

**Comment by bizley** [comment]
I would prefer throwing an exception.
