### ISSUE TITLE
Logger proxy should be in separate repository

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2-symfonymailer#26]
This library contains a proxy allowing us to provide a PSR `LoggerInterface` and route its output to Yii's logger.
This should be in the core or a separate library, it is a useful tool with and without symfony mailer.

I'm happy to create a PR if you can create a new repo, or to create a PR for the Yii2 core, but I think that's feature frozen. Of course I could make this in my own repository as well but it would be better if it lives in yiisoft.

**Comment by samdark** [comment]
https://github.com/samdark/yii2-psr-log-target?

**Comment by SamMousa** [comment]
But this is actually the other way around right? It exposes a PSR3 Logger and sends it to Yii.

**Comment by samdark** [comment]
Is it useful for more cases than the Symfony mailer?

**Comment by SamMousa** [comment]
Any library that supports logging via PSR could have their logs routed to the yii log dispatcher.

**Comment by samdark** [comment]
OK. Do you need a repository? If so, how to name it?

**Comment by SamMousa** [comment]
Any name is fine. Maybe simliar to your `yii2-psr-log-target` but then `yii2-psr-log-source`?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-psr-log-source

**Comment by SamMousa** [comment]
I cannot fork it because it's empty. Can you give me permissions to write to the repo or create an initial commit so that I can fork and create a PR?

**Comment by samdark** [comment]
Created a file.

**Comment by SamMousa** [comment]
Yes, implementing it in this library is now mostly a one-liner, but I have a question.

The implementation looks like this:
```php
$defaultFactories = Transport::getDefaultFactories(null, null, new Logger(Yii::getLogger()));
```

This would take a reference to the `Logger`, however if someone calls `Yii::setLogger` at any time this logger won't be updated to use the new logger. This is of course mutability issue that we have a lot in Yii2. For a library however we should probably support this mutability..

See https://github.com/yiisoft/yii2-psr-log-source/pull/8 for an implementation.
