### ISSUE TITLE
Send email return TRUE but no mail sent

### ISSUE THREAD

**Issue by FedericoBenedetti1976** [yiisoft/yii2-symfonymailer#31]
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.42.1
| Yii SymfonyMailer version | 2.0.3
| SymfonyMailer version     |  ^5.4
| PHP version             | 7.4.29
| Operating system        | ubuntu 18.04

If i change transport settings, always ->send() return true, also if i set xxx.xxx.xx. as host

**Comment by FedericoBenedetti1976** [comment]
The problem is that if i try:
```
        'mailer' => [
            'class' => 'yii\symfonymailer\Mailer',
        ],

```without transport settings, i have back TRUE too

**Comment by samdark** [comment]
We return false if the underlying library is failing for whatever reason. Looks like in your case it does not.

**Comment by FedericoBenedetti1976** [comment]
i'm debugging native code and i find this on BaseMailer.php

```
       ..
        if (array_key_exists('dsn', $config)) {
            $transport = $transportObj->fromString($config['dsn']);
        } elseif(array_key_exists('scheme', $config) && array_key_exists('host', $config)) {
            $dsn = new Dsn(
                $config['scheme'],
                $config['host'],
                $config['username'] ?? '',
                $config['password'] ?? '',
                $config['port'] ?? '',
                $config['options'] ?? [],
            );
           ..

```
So probably if you set Transport param "dns"  it doesn't take your host/username/password/port/etc.. params
But in the official README.md Example there are all params together: https://github.com/yiisoft/yii2-symfonymailer#usage

**Comment by Krakozaber** [comment]
During implementation, I tried to maintain backward compatibility with the yiisoft/yii2-swiftmailer. If you are using DSN, then the password must be contained in it.

**Comment by marcovtwout** [comment]
Note that if you don't specify a transport, a default NullTransport is used and no email is actually being sent. This is different from yiisoft/yii2-swiftmailer that defaults to Sendmail.

**Comment by nd4c** [comment]
> Likely that means that shout01.ot-mail.it accepted it without problems but did not sent it or that DKIM/SPF on that server aren't set correctly so there's delivery problem.

I have a similar if not same problem, trying to use the smtp or smtps transport.  Neither will work correctly.  Does the Symfony Mailer expect to have message bus or something?

I setup my config to be able to switch between Swift or Symfony with appropriate settings.  Swift works fine, Symfony does not return false, but I don't get the emails.

So I tried using a complete fake host and, again, it does not return false.

Please note that I am extending the \yii\symfonymailer\Mailer and \yii\symfonymailer\Message - but I do the same with Swift.  They are very "thin" and are extended to handle changing the "to" for testing and to add in "useDisplayTransport".

The useFileTransport and useDisplayTransport work fine for both Swift and Symfony.

**Comment by nd4c** [comment]
@ FedericoBenedetti1976

You are correct.  If there is a 'dsn' key in the transport config, then the rest is ignored.  So either use a 'dsn' or set up the transport with the proper 'scheme', 'host', etc.

Also, note that the 'scheme' is used by Symfony to choose which Transport Factory to use.  'smtp' and 'smtps' will use the EsmtpTransportFactory to create an EsmtpTransport.

**Comment by nd4c** [comment]
> https://github.com/yiisoft/yii2-symfonymailer/blob/master/src/Mailer.php#L213

The "Exception" from Symfony is a Throwable:
`namespace Symfony\Component\Mailer\Exception;`
`/**`
` * Exception interface for all exceptions thrown by the component.`
` *`
` * @author Fabien Potencier <fabien@symfony.com>`
` */`
`interface ExceptionInterface extends \Throwable`
`{`
`}`

**Comment by nd4c** [comment]
$this->getSymfonyMailer()->send($message); is supposed to return a SentMessage object.  But when I put in code to inspect that - the code is never reached as far as I can tell.  ->send() never returns...

I do not have the debug module set up - will try again with that.

**Comment by nd4c** [comment]
So far I've traced this to the get method for $this->encryptor - it's not returning.  The code never gets to the try catch...

**Comment by nd4c** [comment]
OK - Mailer -> sendMessage needs to catch \Throwable to handle Symfony Mailer exceptions.

**Comment by SamMousa** [comment]
I'm not sure why the `Mailer` would be extended though, I'm skeptical it's the right approach.

Regardless, I think this can be closed right?

**Comment by nd4c** [comment]
Yes.  Sorry for not getting back to this sooner.  It was resolved by your pull request, "Code cleanup."  Thanks for all your work on this!
