### ISSUE TITLE
Can a default sendFrom address be called by updating the configuration file?

### ISSUE THREAD

**Issue by developedsoftware** [yiisoft/yii2-symfonymailer#34]
At the moment whenever we create a message we have to call setFrom() to set the send from address. 

I understand the need for this but could we not have a fallback email - set in the mailer component - to use if setFrom() is not set. 

For example a noreply@somedomain email configured at application level

**Comment by Krakozaber** [comment]
Do you mean this?
`
    'class' => \yii\symfonymailer\Mailer::class,
    'useFileTransport' => false,
    'messageConfig' => [
        'from' => ['noreply@somedomain' => 'noreply'],
    ],
    'transport' => [],
`

**Comment by Krakozaber** [comment]
@developedsoftware talk to me, I miss you :-)

**Comment by developedsoftware** [comment]
Awesome, thank you. 

I will add and close if it works. I assume this means it can be overriden still?

**Comment by developedsoftware** [comment]
Hmm, this doesnt appear to make any difference. The message is not configured as per the messageConfig above.

Any ideas?

**Comment by developedsoftware** [comment]
![Screenshot 2022-07-13 at 16 00 34](https://user-images.githubusercontent.com/19648131/178766042-b98047d5-e2dd-4172-99f2-1f035983c3af.png)

As you can see it doesnt appear to be configuring the component

**Comment by Krakozaber** [comment]
@developedsoftware can you show how you configured mailer ?

**Comment by developedsoftware** [comment]
Sorry thats a class alias. It should be yii. 

Would you expect that to work. If so can re-test and post steps to reproduce here? Its almost like messageConfig is being ignored.
