### ISSUE TITLE
Working within queues support

### ISSUE THREAD

**Issue by pozitronik** [yiisoft/yii2-symfonymailer#35]
### What steps will reproduce the problem?

Trying to use yii2-symfonymailer in queue job.

### What's expected?

Everything is working.

### What do you get instead?

`BadMethodCallException : Cannot serialize Symfony\Component\Mailer\Transport\Smtp\SmtpTransport`
at
` \vendor\symfony\mailer\Transport\Smtp\SmtpTransport.php:356`

### Additional info

At the current moment this extension can't be used in queue jobs (with https://github.com/yarcode/yii2-queue-mailer as example), because that jobs are serialized, but initialized Transport object prevents serialization. Deprecated yii2-swiftmailer extension has no such problem.
The reason is that, the Transport object is initializing [directly in setter](https://github.com/yiisoft/yii2-symfonymailer/blob/1a64cf981796866bcc7124e67ab8a1ef3ca1190a/src/Mailer.php#L80), if it passed as array configuration. It seems, that this behavior can be changed easily. This require just to remove Transport object initialization from `setTransport()` (it all be done in `getTransport()` anyway).
I prepared pull request, that demonstrates my idea, and this code perfectly works within queues. I did not remove the Transport initialization code from setter, in order to not to break current tests, but added a class variable to control the described behavior.

**Comment by Krakozaber** [comment]
@pozitronik, can show how the mailer and the queue service are configured, I use the same package and there are no problems.

**Comment by pozitronik** [comment]
@Krakozaber 
I made a [simple demo](https://github.com/pozitronik/yii2-symfonymailer-issue) for this issue. There is a [test code](https://github.com/pozitronik/yii2-symfonymailer-issue/blob/6da16098f8950ba77f86eb0487ea1ce034c81a6a/tests/unit/MailerQueueSymphonyTest.php#L19):

```php
public function testMailerQueueSymphony():void {
	Yii::$app->set('queue_email', [
		'class' => yii\queue\file\Queue::class,
		'path' => '@runtime/queues/email',
		'ttr' => 3600
	]);
	Yii::$app->set('mailer', [
		'class' => YarCode\Yii2\QueueMailer\Mailer::class,
		'queue' => 'queue_email',
		'syncMailer' => [
			'class' => yii\symfonymailer\Mailer::class,
			'transport' => [
				'scheme' => 'smtp',
				'host' => 'localhost',
				'port' => 25
			],
		],
	]);

	$message = Yii::$app->mailer->compose()
		->setSubject('test email')
		->setFrom('test@email.local')
		->setTextBody(Yii::$app->security->generateRandomString())
		->setTo('test@queueemail.local');
	$this::assertTrue(Yii::$app->mailer->send($message));
}
```

It'll fail with reason `Cannot serialize Symfony\Component\Mailer\Transport\Smtp\SmtpTransport` when queue job has to serialize.

**Comment by pozitronik** [comment]
@Krakozaber
Can you confirm the problem?

**Comment by SamMousa** [comment]
Why are you serializing services? Shouldn't you just serialize the message?

**Comment by pozitronik** [comment]
> Shouldn't you just serialize the message?

I would like to, but the message object already contains an initialized Transport object. My point is to remove initialized object, and replace it to its configuration (as in the SwiftMailer).

**Comment by SamMousa** [comment]
> I would like to, but the message object already contains an initialized Transport object.

That's just bad design of the core to be honest. Specifically this fragment:
```php
abstract class BaseMessage extends BaseObject implements MessageInterface
{
    /**
     * @var MailerInterface the mailer instance that created this message.
     * For independently created messages this is `null`.
     */
    public $mailer;
```
The only reason this exists is so that you can call `$message->send()` instead of $mailer->send($message)`.
Would it not work to unset `$mailer` before serializing?
Thereby not serializing the mailer and any of it's config.

**Comment by pozitronik** [comment]
>The only reason this exists is so that you can call `$message->send()` instead of `$mailer->send($message)`.

Agreed.

>Would it not work to unset `$mailer` before serializing?

[Yes, it is working](https://github.com/pozitronik/yii2-symfonymailer-issue/blob/aaa7e48643d52948b50410042e91edfb58dc490d/tests/unit/MailerQueueSymphonyTest.php#L84).

**Comment by pozitronik** [comment]
> ```
> return ['email', 'charset'];
> ```

umm... It makes sense, but i don't see this code nowhere in the component 👀.

**Comment by SamMousa** [comment]
It's part of this PR: https://github.com/yiisoft/yii2-symfonymailer/pull/27
