### ISSUE TITLE
Implementation try catch for debugging

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [yiisoft/yii2-symfonymailer#37]
### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.45
| Yii SymfonyMailer version | 2.0.3
| SymfonyMailer version     | >= 5.4.0
| PHP version             | 7.4.20
| Operating system        | Ubuntu 20.04

How to catch error when sending email. My problem is, when in localhost is success, but in production is failed.

```php
 public function kirimEmailPengajuanLoginAccount($userYangMengajukanId): bool
    {
        $settings = Yii::$app->settings;
        $emailTo = $settings->get('Email.pengaktifanUserAccount');
        $senderEmail = $settings->get('Email.senderEmail');
        $senderName = $settings->get('Email.senderName');

        $userYangMengajukan = User::findOne($userYangMengajukanId);

        $mailer = Yii::$app->mailer->compose('pengajuan_user_account', [
            'model' => $this,
            'userYangMengajukan' => $userYangMengajukan
        ])
            ->setTo($emailTo)
            ->setFrom([$senderEmail => $senderName])
            ->setReplyTo($emailTo)
            ->setSubject('Permohonan pengaktifan user account atas nama: ' . $this->nama);

        try {
            return $mailer->send();
        } catch (TransportExceptionInterface $e) {
            $this->addError('nama', $e->getDebug());
        }

        return false;


    }
```

I got empty array in 'nama' attribute.
Thanks for the suggestion

**Comment by nd4c** [comment]
You can simply use $e->getMessage() instead of $e->getDebug();
`$this->addError('name', $e->getMessage());`

Apparently the EsmtpTransport does not append Debug info to the TransportException.

**Comment by nd4c** [comment]
Also, since you would not be using the getDebug() method you can catch \Throwable instead of the TransportExceptionInterface if you prefer.  You can, of course use both, catching the TrasportExecption first - that way you can check to see if the error was a Time Out and then resend the email - though you would want to wrap this in a counter loop to prevent too many retries and causes the UI to hang.

**Comment by nd4c** [comment]
I'm sorry, I believe there's a bug in the yii\symfonymailer.  The sendMessage method catches \Exceptions and (at least in PHP 8.1) that catches the TransportException.  So the Exception never passes.  And the sendMessage does not return the "SentMessage" object back to the send() method of the BaseMailer.

I could be wrong, (it happens ;-) ), but at this point my suggestion, until this is corrected, is to extend the Mailer class and the sendMessage() method.  Just be sure to make sure the correct Message class and that you copy the required private properties:
`private ?SMimeEncrypter $encryptor = null;`
`private $signer = null;`
`private array $dkimSignerOptions = [];`

The new sendMessage method can either not catch the Exception (simple) or it can pass back the SentMessage object, which I have not tested so I don't know if that will work.

**Comment by SamMousa** [comment]
The issue here is that the contract for mailers https://github.com/yiisoft/yii2/blob/master/framework/mail/MailerInterface.php does not clearly specify that exceptions may be thrown. (And the return value of type boolean suggests it isn't..)

But I agree that it's better to just have exceptions.
