### ISSUE TITLE
Document TransportFactoryInterface: Adding Socket Timeout Option to Mailer

### ISSUE THREAD

**Issue by nd4c** [yiisoft/yii2-symfonymailer#40]
### What steps will reproduce the problem?
Migrate from Swift Mailer to Symfony Mailer
### What's expected?
SwiftMailer has a transport->timeout property that can be set in the config.  Defaults to 30.
### What do you get instead?
The Symfony Mailer does not have an exposed way to set the timeout for the EsmtpTransport.  (There is a value and a setter Method, but there is no way to call it since the transport is private...)

### Additional info
If the Symfony Transport timeout property is not set it will default to the php.ini setting, 'default_socket_timeout'  which default to 60.

We can wrap the mailer->send() call, but it would be nice to be able to config the Mailer's timeout value.

We cannot add a new property to the transport itself, but we can add one to the yii Mailer class.

Possible solution:

    class Mailer extends BaseMailer
     {
        /**
         * @var int transport_timeout defaults to 0 since this would only apply to smtp/smtps transports.
         */
        public $transport_timeout = 0;
        ...
        /**
         * {@inheritDoc}
         *
         * @throws TransportExceptionInterface If sending failed.
         */
        protected function sendMessage($message): bool
        {
            ...
            try {
                if (!empty($this->transport_timeout) && (int) $this->transport_timeout > 0) {
                    $default_socket_timeout = ini_set('default_socket_timeout', (int) $this->transport_timeout);
                }
                $this->getSymfonyMailer()->send($message);
            } catch (\Exception $exception) {
                Yii::getLogger()->log($exception->getMessage(), \yii\log\Logger::LEVEL_ERROR, __METHOD__);
                // need to re-throw the exception so that caller can extract transport errors
                throw($exception);
            } finally {
                if (!empty($default_socket_timeout) && (int) $default_socket_timeout > 0) {
                    ini_set('default_socket_timeout', (int) $default_socket_timeout);
                }
            }
            return true;
        }
    }

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.45
| Yii SymfonyMailer version | 2.0.3
| SymfonyMailer version     | v6.0.11
| PHP version             | 8.1.9
| Operating system        | Linux Mint 20.3 with Kernel Linux 5.15.0-46-generic

**Comment by SamMousa** [comment]
Copied from https://github.com/yiisoft/yii2-symfonymailer/pull/27#issuecomment-1216300900

You'd use a wrapper class (composition instead of inheritance) since Symfony even goes so far as to make their classes final so you cannot extend them.
```php
class SmtpTransportWithTimeoutFactory implements TransportFactoryInterface {
    public function __construct(private TransportFactoryInterface $factory, private float $timeout)
    {
    }

    public function create(Dsn $dsn): TransportInterface
    {
        $result = $this->factory->create($dsn);
        if ($result instanceof SmtpTransport) {
            $result->getStream()->setTimeout($this->timeout);
        }
        return $result;
    }

    public function supports(Dsn $dsn): bool {
        return $this->factory->supports($dsn);
    }
}
```

**Comment by nd4c** [comment]
Thanks!  This will be a big help.  I hadn't realized that Symfony classes were final.  I'd suggest even including this Factory with the Yii2 extension.

**Comment by nd4c** [comment]
I was thinking that lack of control for the timeout of the Symfony smtp/smtps Transport was a major hurdle for migrating from Swift to Symfony.  

It might be helpful in the Migrating From yiisoft/yii2-swiftmailer section (https://github.com/yiisoft/yii2-symfonymailer#migrating-from-yiisoftyii2-swiftmailer) to include the sample wrapper and how to wire it up in the config file.

**Comment by SamMousa** [comment]
Feel free to make a PR for the docs!
