### ISSUE TITLE
No exception is thrown to caller when sending mail fails

### ISSUE THREAD

**Issue by RickKukiela** [yiisoft/yii2-symfonymailer#43]
Ref line: https://github.com/yiisoft/yii2-symfonymailer/blob/716243e9e8250c71e30280e287dbcd7ff9f2507f/src/Mailer.php#L213

This `catch` does not re-throw the exception and instead does its own logging and returns false. There should be a way to suppress this behavior and let the exception be caught by the caller.

I have my own logging setup and now I have no way of logging the actual exception the way I want to after upgrading from the old swiftwmailer component.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |
| Yii SymfonyMailer version |
| SymfonyMailer version     |
| PHP version             |
| Operating system        |

**Comment by Swanty** [comment]
Looks like its fixed in 3.0.0

https://github.com/yiisoft/yii2-symfonymailer/blob/291c00979a9bf14e89bb5230ddd700a6dc130e51/src/Mailer.php#L144

**Comment by RickKukiela** [comment]
:) nice!
