### ISSUE TITLE
Mailer re-enable TLS support after manual disable

### ISSUE THREAD

**Issue by delikates-nsk** [yiisoft/yii2-symfonymailer#47]
### What steps will reproduce the problem?
```php
//I disabled work with tls support because I am connecting to localhost and I have a self-signed certificate installed on the mail server

$transport = new EsmtpTransport('localhost', 25, FALSE ); //third parameter equal to false disables tls support

$transport->setUsername( 'username' )
          ->setPassword( 'password' );

$mailer = new Mailer($transport);
$message = (new Email())->from( 'nevermind@nevermind.tld')
                        ->subject( 'subject' )
                        ->to('nevermind@nevermind.tld')
                        ->text('body');
try {
    $mailer->send($message);
} catch (TransportException $e) {
   $lastErrorMsg = $e->getMessage();
} catch( \Throwable $e) {
   $lastErrorMsg = $e->getMessage();
} catch (\Exception $e) {
   $lastErrorMsg = $e->getMessage();
}

var_dump( $lastErrorMsg );
die();

```

### What's expected?
Inside `vendor\symfony\mailer\Transport\Smtp\EsmtpTransport.php` source code
```php
    protected function doHeloCommand(): void
    {
        if (!$capabilities = $this->callHeloCommand()) {
            return;
        }

        /** @var SocketStream $stream */
        $stream = $this->getStream();
        // WARNING: !$stream->isTLS() is right, 100% sure :)
        // if you think that the ! should be removed, read the code again
        // if doing so "fixes" your issue then it probably means your SMTP server behaves incorrectly or is wrongly configured
        if (!$stream->isTLS() && \defined('OPENSSL_VERSION_NUMBER') && \array_key_exists('STARTTLS', $capabilities)) {
            $this->executeCommand("STARTTLS\r\n", [220]);

            if (!$stream->startTLS()) {
                throw new TransportException('Unable to connect with STARTTLS.');
            }

            $capabilities = $this->callHeloCommand();
        }

        if (\array_key_exists('AUTH', $capabilities)) {
            $this->handleAuth($capabilities['AUTH']);
        }
    }
```
the following line of code causes that, despite the fact that I disabled tls earlier, if the mail server responds with tls support after the hello, the secure connection attempt will still continue. but it's correct, if I disabled tls support, then it should remain disabled, and the `STARTTLS` command should not be sent to the mail server

```php
...
if (!$stream->isTLS() && \defined('OPENSSL_VERSION_NUMBER') && \array_key_exists('STARTTLS', $capabilities)) {
...
```

### What do you get instead?
Error message:
`Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.47
| Yii SymfonyMailer version | 3.0.0
| SymfonyMailer version     | 5.4
| PHP version             | 7.4.30
| Operating system        | Ubuntu (Server) 18.04.6 LTS

**Comment by Swanty** [comment]
Add `verify_peer=0` to your dsn url to fix the problem with self-signed certificate

**Comment by delikates-nsk** [comment]
Inside `vendor\symfony\mailer\Transport\Smtp\EsmtpTransportFactory.php` source code you can see
```php
public function create(Dsn $dsn): TransportInterface
    {
        $tls = 'smtps' === $dsn->getScheme() ? true : null;
        $port = $dsn->getPort(0);
        $host = $dsn->getHost();

        $transport = new EsmtpTransport($host, $port, $tls, $this->dispatcher, $this->logger);

        if ('' !== $dsn->getOption('verify_peer') && !filter_var($dsn->getOption('verify_peer', true), \FILTER_VALIDATE_BOOLEAN)) {
            /** @var SocketStream $stream */
            $stream = $transport->getStream();
            $streamOptions = $stream->getStreamOptions();

            $streamOptions['ssl']['verify_peer'] = false;
            $streamOptions['ssl']['verify_peer_name'] = false;

            $stream->setStreamOptions($streamOptions);
        }
        ...
}
```

Thus, this option will simply disable the certificate validity check, but will not disable the attempt to establish a TLS connection, despite the fact that I explicitly forbade it.

The mail server may be configured incorrectly and display startls in the list of supported authorization methods without actually supporting it. for such cases, an explicit indication not to connect using this method can help. in my opinion, this is a bad idea, despite the explicit prohibition on the part of the programmer, anyway, somewhere inside the code of the library used, this prohibition is bypassed

**Comment by Swanty** [comment]
As I understand `new EsmtpTransport('localhost', 25, FALSE );` 3rd argument simply states that this is an explicit TLS connection (opposed to implicit TLS) and thus by supplying `false` it will establish connection in cleartext first and if server reports `STARTTLS` capability available then it will attempt to upgrade to TLS.  
If it was `true` then I guess it would attempt to establish TLS from the start  

Explicit TLS/SSL = establish connection in cleartext and upgrade to TLS (if server reports it has STARTTLS capability - usually port 587) and if server doesn't report this capability then all communication would continue in cleartext.
Implicit TLS/SSL = establish connection in TLS/SSL from the start (usually port 465)  

Anyways, I agree that Symfony Mailer is missing a feature to ignore STARTTLS capability if the server reports it, but that is a problem with https://github.com/symfony/mailer not this repository. This repository is a wrapper around Symfony Mailer for using in yii2.  
You can create a new issue about Symfony Mailer in https://github.com/symfony/symfony/issues

**Comment by samdark** [comment]
Closing since, as @Swanty said, it can't be fixed in Yii2 repository.
