### ISSUE TITLE
Exception 'Symfony\Component\Mime\Exception\LogicException' with message 'A message must have a text or an HTML part or attachments.'

### ISSUE THREAD

**Issue by massikage** [yiisoft/yii2-symfonymailer#56]
Hi all,
I am using Wampserver, I configured yiisoft/yii2-symfonymailer like follows :

App config:
![Capture d’écran 23-03-2023 10 40 33](https://user-images.githubusercontent.com/57631388/227168538-3970b587-ba31-4b8a-a3a2-5802d8c57390.jpg)
Send Email:
![Capture d’écran 23-03-2023 10 44 55](https://user-images.githubusercontent.com/57631388/227169182-9ae17b12-3f19-4c7f-a029-ad5d7d9769ce.jpg)

when sending an email, it shows me this error
![Capture d’écran 23-03-2023 10 46 02](https://user-images.githubusercontent.com/57631388/227169763-df88f848-11f9-4eff-b2a8-006cfa96350e.jpg)

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.47
| Yii SymfonyMailer version | 3.0.0
| SymfonyMailer version     |
| PHP version             | 8.2.3
| Operating system        | Windows 10

**Comment by mtangoo** [comment]
@massikage does it still happen with the latest version?

**Comment by mtangoo** [comment]
I will close it, since there is no response.
Feel free to reopen if issue still happen!
