### ISSUE TITLE
Readme Timeout Example does not work.

### ISSUE THREAD

**Issue by ricksmort** [yiisoft/yii2-symfonymailer#62]
The example given to expand SymfonyMailer found in the [read me ](https://github.com/yiisoft/yii2-symfonymailer#migrating-from-yiisoftyii2-swiftmailer) setting a timeout with the example given (copying and pasting), throws error(s). I ended up doing a fresh install, of the newest version of Yii2 running on my development server (PHP 8.1)

The error:
`Setting unknown property: yii\symfonymailer\Mailer::transportFactory`

On my production server, I've attempted to setup Symfony mailer, once again copying and pasting the example code given to setup a timeout feature only to discover that Symfony mailer interferes with the Yii2 Log Email target, disabling this feature prevents the error:

`PHP Warning: Attempt to read property “enabled” on array in /vendor/yiisoft/yii2/log/Dispatcher.php on line 190`

I've posted about my struggles with Symfony mailer on the community forum [https://forum.yiiframework.com/t/swiftmailer-to-symfonymailer-timeout-expansion-yii2-log-email-target/135773](https://forum.yiiframework.com/t/swiftmailer-to-symfonymailer-timeout-expansion-yii2-log-email-target/135773)

Yii2 version: 2.0.49.3
Yii2 Symfony mailer version: v6.0.19
PHP version: 8.1

**Comment by mtangoo** [comment]
Thanks for reporting. I can confirm the report. I will investigate and fix

**Comment by samdark** [comment]
@mtangoo any update?

**Comment by mtangoo** [comment]
@samdark I expect to revisit all these issues early next year.
I hope to fix them all.

**Comment by mtangoo** [comment]
@ricksmort can you set composer.json version of this extension to `dev-master` and try the latest example if you have any further issues? Only big change is that the extension now requires PHP8.1, which I guess is not a big deal. But nice to mention upfront!

**Comment by ricksmort** [comment]
Hey @mtangoo, that appears to have done the trick! Might I add a small suggestion for the read me, re-add the "'class' => app\utils\CustomSmtpFactory::class," instead of it being "'class' => CustomSmtpFactory::class," since the example given for the CustomSmtpFactory.php is within the folder "utils".

Thank you everyone!

**Comment by mtangoo** [comment]
Thanks for testing and pointing that out.
The example is now fixed.

We will release 4.0.0 soon so that you don't have to depend on dev version
