### ISSUE TITLE
Dependency issues on 7.4

### ISSUE THREAD

**Issue by winternet-studio** [yiisoft/yii2-symfonymailer#64]
### What steps will reproduce the problem?

I required yiisoft/yii2-symfonymailer (^3.0) but on PHP 7.4 I get:

```
  Problem 1
    - psr/log is locked to version 3.0.0 and an update of this package was not requested.
    - psr/log 3.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 2
    - symfony/mime is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/mime v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 3
    - psr/log 3.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
    - symfony/mailer v5.4.31 requires psr/log ^1|^2|^3 -> satisfiable by psr/log[3.0.0].
    - symfony/mailer is locked to version v5.4.31 and an update of this package was not requested.
```

### What's expected?

v3 should work fine on 7.4.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.41.1
| Yii SymfonyMailer version |
| SymfonyMailer version     |
| PHP version             | 7.4
| Operating system        | Linux

**Comment by mtangoo** [comment]
Hi @winternet-studio,
is this still a valid issue?
Please confirm

**Comment by samdark** [comment]
Likely not https://github.com/yiisoft/yii2-symfonymailer/blob/master/composer.json#L28

**Comment by mtangoo** [comment]
Thanks for point that. I will close the ticket for now.
